package com.ollycredit.ui.terms_conditions;

import android.os.Bundle;
import android.support.v7.widget.Toolbar;
import android.text.Html;
import android.view.Menu;
import android.view.MenuItem;
import android.webkit.WebView;
import android.widget.TextView;

import com.ollycredit.OllyCreditApplication;
import com.ollycredit.R;
import com.ollycredit.base.BaseActivity;
import com.ollycredit.utils.GlobalConstants;
import com.ollycredit.utils.helpers.HelperClass;

import butterknife.BindView;
import butterknife.ButterKnife;

public class LegalTermsConditionActivity extends BaseActivity {

    @BindView(R.id.toolbar_legal)
    Toolbar navToolbar;

    @BindView(R.id.tv_terms)
    TextView tv_terms;



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_legal_terms_condition);


        getActivityComponent().inject(this);
        ButterKnife.bind(this);

        setUp();

    }

    @Override
    public void onResume() {
        super.onResume();
        OllyCreditApplication.getInstance().trackScreenView(this.getClass().getSimpleName());
//        OllyCreditApplication.getInstance().trackEvent(
//                GlobalConstants.CATEGORY_ONBOARDING,
//                GlobalConstants.ACTION_GOTO,
//                GlobalConstants.LABLE_TO_HOME
//        );
    }


    @Override
    protected void setUp() {

        setSupportActionBar(navToolbar);

        tv_terms.setText(Html.fromHtml("<!DOCTYPE html>\n" +
                "<html lang=\"en\">\n" +
                "<head>\n" +
                "    <meta charset=\"UTF-8\">\n" +
                "</head>\n" +
                "<body>\n" +
                "\n" +
                "<h2>TERMS OF USE</h2>\n" +
                "    \n" +
                "        <h3>1.General</h3>\n" +
                "        <p>In terms of the Information Technology Act, 2000, this document is an electronic record. Being generated by a\n" +
                "            computer system it does not require any physical or digital signatures.\n" +
                "            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology\n" +
                "            (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy\n" +
                "            and\n" +
                "            Terms\n" +
                "            of Use for access or usage of ollycredit.in\n" +
                "            This Website by the URL ollycredit.in and all the Web – pages, hyperlinks, tools and Services provided there\n" +
                "            under\n" +
                "            is owned and operated by Millennial Card Technologies Private Limited (hereafter referred to as “Olly”), a\n" +
                "            company\n" +
                "            incorporated under The Companies Act 2013 with its registered office at New-Delhi, Delhi.\n" +
                "            Olly’s (“Our”, “Us”, “We”, “Website”, “Site”) Website and mobile application (“Application”) come as a\n" +
                "            medium\n" +
                "            for\n" +
                "            Macro limit credit card (“Services”).\n" +
                "            The expressions “You”, “Your” or “User”, whenever the context so requires, for the purposes of these Terms\n" +
                "            of\n" +
                "            Use,\n" +
                "            shall mean any natural or legal person who may create by registration, membership account on this Website or\n" +
                "            Application or agree to avail Our Services through this Website or Application, or otherwise access Our\n" +
                "            Website\n" +
                "            or\n" +
                "            Application.\n" +
                "            These terms and conditions (“Terms of Use”) shall govern your access to and use of the Services however\n" +
                "            accessed, as\n" +
                "            well as any and all information of whatever kind and nature appearing on the Website or Application or\n" +
                "            otherwise\n" +
                "            available through the Services. Please read these Terms of Service carefully before using the Site and/or\n" +
                "            Application; your access to and use of the Services is conditioned on your acceptance of and compliance with\n" +
                "            these\n" +
                "            Terms of Use. By downloading and installing the Application, accessing the Site or using the Services in any\n" +
                "            way,\n" +
                "            you agree to and are hereby bound by these Terms of Use. If you do not agree to all of the terms and\n" +
                "            conditions\n" +
                "            contained herein, do not use the Services, or access them through the Site or Application. Unless explicitly\n" +
                "            stated\n" +
                "            otherwise, any new features which may be added to the Services, including the release of new services or\n" +
                "            capabilities, are subject to these Terms of Use.\n" +
                "            We may, in our sole discretion, make changes to these Terms of Use, from time to time with or without notice\n" +
                "            to\n" +
                "            you.\n" +
                "            Each time changes are made to these Terms of Use, a revised version of these Terms of Use, will be posted in\n" +
                "            the\n" +
                "            Application and Website. Your continued use of the Service following such changes constitutes your\n" +
                "            acceptance of\n" +
                "            any\n" +
                "            such changes. You can review and are encouraged to check, from time to time, the most current version of\n" +
                "            these\n" +
                "            Terms\n" +
                "            of Service. At all times, the latest version of these Terms of Service shall be binding and prevail over any\n" +
                "            other\n" +
                "            version. Furthermore, We reserve the right to amend, discontinue, limit, disable, terminate, or cancel any\n" +
                "            feature\n" +
                "            of the Services at any time.\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "\n" +
                "    \n" +
                "        <h3>2.Privacy Policy</h3>\n" +
                "        <p>\n" +
                "            We respect the privacy of others. Any information that you provide us through the Services is subject to Our\n" +
                "            Privacy\n" +
                "            Policy. Your use of the Services constitutes your consent to the collection and use of your certain\n" +
                "            information,\n" +
                "            as\n" +
                "            described in our Privacy Policy\n" +
                "        </p>\n" +
                "    \n" +
                "\n" +
                "    \n" +
                "        <h3>3.Member Registration</h3>\n" +
                "        <p>\n" +
                "            Users as may be approved by Olly shall have the right to use the Service provided by Olly via its Website\n" +
                "            and/or\n" +
                "            Application.\n" +
                "            Users who are competent to contract under the Indian Contract Act, 1872, are eligible to register themselves\n" +
                "            as\n" +
                "            members on the Website or Application and can avail Our Services. Persons who are competent to contract\n" +
                "            would mean\n" +
                "            and include every person who, (i) has completed 18 years of age (as per The Indian Majority Act, 1875); (ii)\n" +
                "            is of\n" +
                "            sound mind; and (iii) not disqualified from contracting by any law for the time being in force in India.\n" +
                "            In addition to the aforementioned conditions, User shall also have a valid Permanent Account Number (“PAN”)\n" +
                "            and a\n" +
                "            valid Aadhar card, to be eligible to avail the Services of Olly on the Website or Application.\n" +
                "            You would be required to sign up on the Website or Application by providing certain personal details such as\n" +
                "            name,\n" +
                "            e-mail address and telephone number. You agree to provide true, accurate, current and complete information\n" +
                "            about\n" +
                "            yourself as prompted by the registration form. If You provide information that is untrue, inaccurate, not\n" +
                "            current or\n" +
                "            incomplete, or We have reasonable grounds to suspect that You have provided such information, then Olly may\n" +
                "            (in\n" +
                "            addition to any other rights or remedies available to us) refuse registration, suspend access to all current\n" +
                "            or\n" +
                "            future use of the Website or Application and the Services (or any portion thereof) permanently.\n" +
                "            When You sign up on the Website, Your personal information will be registered automatically in Our database\n" +
                "            which\n" +
                "            will be maintained and used by the Website in accordance with the Privacy Policy.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "\n" +
                "    \n" +
                "        <h3>4.Usage conditions</h3>\n" +
                "        <p>\n" +
                "            Users agree to use the Services only for purposes that are permitted by a) the User Terms and b) any\n" +
                "            applicable laws\n" +
                "            as amended from time to time for the time being in force.\n" +
                "            By using the Website and/or Application You agree not to:</p>\n" +
                "            a. authorize others to use your account;\n" +
                "            <br><br>b. assign or otherwise transfer Your account to any third person or legal entity;\n" +
                "            <br><br>c. use the Service or Website or Application for unlawful purposes, including but not limited to sending\n" +
                "                or\n" +
                "                storing\n" +
                "                any unlawful material or for fraudulent purposes;\n" +
                "            \n" +
                "            <br><br>d. use the Service or Website or Application to cause nuisance, annoyance or inconvenience;\n" +
                "            <br><br>e. use the Service or Website or Application with an incompatible or unauthorized device;\n" +
                "            <br><br>f. impair the proper operation of the network and/or interfere with or disrupt the integrity or\n" +
                "                performance\n" +
                "                of the\n" +
                "                Website or Service or Application;\n" +
                "            \n" +
                "            <br><br>g. reverse engineer or access the Service or Website or Application in order to design or build a\n" +
                "                competitive\n" +
                "                product or service, design or build a product using similar ideas, features, functions or graphics of\n" +
                "                the\n" +
                "                Website or\n" +
                "                Application or copy any ideas, features, functions or graphics of the Website or Application,\n" +
                "            \n" +
                "            <br><br>h. launch an automated program or script, including, but not limited to, web spiders, web crawlers, web\n" +
                "                robots, web\n" +
                "                ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per\n" +
                "                second, or\n" +
                "                unduly burdens or hinders the operation and/or performance of the Website or Service or Application;\n" +
                "            \n" +
                "            <br><br>i. try to harm the Service or Website or Application in any way whatsoever;\n" +
                "            <br><br>j. disclose information designated as confidential by Olly, without Olly’s prior written consent; and\n" +
                "            \n" +
                "            <br><br>k. copy or distribute the Service or Website or Application or other Olly content without written\n" +
                "                permission\n" +
                "                from\n" +
                "                Olly.\n" +
                "            \n" +
                "        <p>You are solely responsible for any breach of your obligations under this agreement (including financial\n" +
                "            obligations)\n" +
                "            and for the consequences (including any loss or damage which Olly may suffer) of any such breach.</p>\n" +
                "\n" +
                "    \n" +
                "        <h3>5.Terms of Credit</h3>\n" +
                "        <p>\n" +
                "            The User shall be entitled to a credit limit of Rs. 20,000 (Rupees Twenty Thousand), with subject to\n" +
                "            satisfaction of\n" +
                "            certain conditions, as provided herein in this Terms of Use.\n" +
                "            The User shall be entitled to credit limit which shall not be lower than Rs. 1100 and which shall not exceed\n" +
                "            Rs.\n" +
                "            20,000 (“Credit Limit”) when the User signs up on the Website and/or Application.\n" +
                "            The User shall further be entitled to an increase in the Credit Limit by a sum of Rs. 500 (Rupees Five\n" +
                "            Hundred),\n" +
                "            following the verification of the PAN of the User on the Website and/or Application.\n" +
                "            The User shall further be entitled to an increase in the Credit Limit by a sum of Rs. 1,000 (Rupees One\n" +
                "            Thousand),\n" +
                "            following the verification by the User of his or her debit card.\n" +
                "            The User shall further be entitled to an increase in the Credit Limit by a sum of Rs. 3,500 (Rupees Three\n" +
                "            Thousand\n" +
                "            and Five Hundred), following the fulfilment by the User of his or her know your customer (“KYC”)\n" +
                "            obligations. The\n" +
                "            User may fulfil his or her KYC obligation by carrying out an e-KYC via the Website and/or Application, or by\n" +
                "            scheduling an appointment for a visit by a representative of Olly to fulfil the KYC obligations in person.\n" +
                "            The User shall further be entitled to an increase in the Credit Limit by a sum of Rs. 2,500 (Rs. Two\n" +
                "            thousand and\n" +
                "            five hundred) by making 2 (two) repayments with respect to the credit availed via the Website and/or\n" +
                "            Application.\n" +
                "            Further provided that Olly may, in its sole discretion, increase the Credit Limit of the User or decrease\n" +
                "            the Credit\n" +
                "            Limit of the User or forfeit any such increase in the Credit Limit of the User.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>6.Payment Terms</h3>\n" +
                "        <p>\n" +
                "            You, the User, acknowledge and accept that all payments, with respect to the credit obtained by the User via\n" +
                "            the\n" +
                "            Website and/or Application, shall only be made by means of a valid debit card.\n" +
                "            The invoice for the credit obtained by the User by means of the Website and/or Application, shall be\n" +
                "            conveyed to You\n" +
                "            on Your e-mail address, via SMS on Your mobile number, as have been provided to Olly by You, and via the\n" +
                "            Olly\n" +
                "            Website and/or Application on the last day of every month. You shall be liable to make the payment by the\n" +
                "            10th\n" +
                "            (tenth) day of every month (“Payment Date”)\n" +
                "            The invoice sent by Olly to You shall display the total credit obtained by You via the Website and/or\n" +
                "            Application\n" +
                "            (“Total Credit”). With respect to the total credit obtained by You via the Website and/or Application, the\n" +
                "            invoice\n" +
                "            shall also display the total payment due to settle the Total Credit (“Total Payment Due”) andthe minimum\n" +
                "            payment due\n" +
                "            to be paid by You with respect to the Total Credit availed by You via the Website and/or Application to\n" +
                "            continue\n" +
                "            Your use of the Services (“Minimum Payment Due”).\n" +
                "            In the event of Your failure to make payment of the Total Payment Due before the expiry of the Payment Date,\n" +
                "            Olly\n" +
                "            shall charge an interest of three percent (3%) on the remaining amount of credit.\n" +
                "            In the event of Your failure to make payment of the Minimum Payment Due before the expiry of the Payment\n" +
                "            Date, Olly\n" +
                "            shall temporarily suspend Your use of its sServices\n" +
                "            In subsequence to the temporary suspension of Your Services by Olly, You shall be liable to make payment of\n" +
                "            an\n" +
                "            amount of money or such additional sums of money, that shall be equal to the Minimum Payment Due within a\n" +
                "            period of\n" +
                "            seven (7) days following the expiry of the Payment Date (“Extended Payment Date”). In the event of your\n" +
                "            failure to\n" +
                "            make payment of such amount of money or such additional sums of money, that shall be equal to the Minimum\n" +
                "            Payment\n" +
                "            Due before the expiry of the Extended Payment Date, Olly shall permanently suspend Your use of its Services.\n" +
                "            In the event of Your failure to make payment as has been provided for in the aforementioned paragraph, Olly\n" +
                "            shall\n" +
                "            declare You as a defaulter and Olly shall further be entitled to share all the information, as has been\n" +
                "            provided by\n" +
                "            You to Olly, and all the information obtained by Olly during Your use of its Website and/or Application with\n" +
                "            ___ and\n" +
                "            other financial institutions including but not limited to banks and other credit providing entities.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>7.Content</h3>\n" +
                "        <p>\n" +
                "            A variety of information, text, graphics, software, graphics, photos, data, video, audio-visual\n" +
                "            combinations,\n" +
                "            interactive features and other materials You may view on, or access through the Service (“Content”) is\n" +
                "            available on\n" +
                "            the Website and Application. The Content available on the Website and Application shall be used solely for\n" +
                "            Your\n" +
                "            non-commercial use and/or to benefit from the products, Services intimated on the Website and Application.\n" +
                "            No right,\n" +
                "            title or interest in any Content is transferred to You, whether as a result of downloading or reproducing\n" +
                "            such\n" +
                "            Content or otherwise. We reserve complete ownership, title and full intellectual property rights in all\n" +
                "            Content\n" +
                "            uploaded by Us. Except as expressly authorized by this Terms of Use, You may not use, alter, copy,\n" +
                "            distribute,\n" +
                "            transmit, or derive another work from any Content obtained from Us or the Service. As an account holder on\n" +
                "            the\n" +
                "            Website or Application, You may view Content.\n" +
                "            All Content on the Website and Application is either owned or licensed to Us, and is subject to copyright,\n" +
                "            trade\n" +
                "            mark rights, and other intellectual property rights of the Website and Application.\n" +
                "\n" +
                "\n" +
                "    \n" +
                "        <h3>8.Use Of Message Boards, Chat Rooms And Other Communication Forums</h3>\n" +
                "        <p>\n" +
                "            This Site and Application may contain message/bulletin boards, chat rooms, or other message or communication\n" +
                "            facilities (collectively, “Posts or “Forums”), You agree to use the Forums only to send and receive messages\n" +
                "            and\n" +
                "            material that are proper and related to the particular Forum. By way of example, and not as a limitation,\n" +
                "            You agree\n" +
                "            that when using a Posts or Forum, You shall not do any of the following:\n" +
                "            Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and\n" +
                "            publicity) of others. Publish, post, distribute or disseminate any defamatory, infringing, obscene, indecent\n" +
                "            or\n" +
                "            unlawful material or information. Upload files that contain software or other material protected by\n" +
                "            intellectual\n" +
                "            property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have\n" +
                "            received\n" +
                "            all necessary consents. Upload files that contain viruses, corrupted files, or any other similar software or\n" +
                "            programs that may damage the operation of another's computer. Conduct or forward surveys, contests, or chain\n" +
                "            letters. Download any file posted by another user of a Forum that you know, or reasonably should know,\n" +
                "            cannot be\n" +
                "            legally distributed in such manner. All Forums are public and not private communications. Chats, postings,\n" +
                "            conferences, and other communications by other users are not endorsed by Olly, and such communications shall\n" +
                "            not be\n" +
                "            considered reviewed, screened, or approved by Olly. Olly reserves the right for any reason to remove without\n" +
                "            notice\n" +
                "            any contents of the Forums received from users, including without limitation message board postings.\n" +
                "            In no event shall the Site and/or Application be held responsible for any Posts nor does Olly, Site or\n" +
                "            Application\n" +
                "            represent or endorse the accuracy or reliability of any advice, opinion, statement, suggestion or other\n" +
                "            information\n" +
                "            on the Posts nor shall Olly be liable for any loss or damages resulting from their use and/or appearance on\n" +
                "            the\n" +
                "            Site.\n" +
                "            By providing a Post to the Site and/or Application, you undertake, represent and warrant to Olly that you\n" +
                "            have all\n" +
                "            necessary rights in and to that Post and all information it contains and that no such Post shall infringe\n" +
                "            any\n" +
                "            rights, of third parties, including without limitation, intellectual property rights or other rights of any\n" +
                "            third\n" +
                "            parties or be otherwise defamatory, slanderous or hurtful to any particular person or group of people.\n" +
                "            By submitting any Post, you grant Olly and its associate companies, a perpetual, worldwide, royalty-free,\n" +
                "            irrevocable, non-exclusive licence to use, and authorise others to use the Post in whole or in part, in any\n" +
                "            and all\n" +
                "            media, now known or hereafter developed, alone, or together or as part of any other type of material of any\n" +
                "            kind or\n" +
                "            nature.\n" +
                "            Olly, Site and/or Application will have the right to monitor, remove, suspend, destroy, use and change any\n" +
                "            Post\n" +
                "            and/or content that is available on or via any chat area or our Site or Application generally, in any manner\n" +
                "            that\n" +
                "            Olly may determine, in its sole discretion, at any time. Although Olly endeavours to periodically monitor\n" +
                "            the\n" +
                "            content posted on this Site and Application, the Site and/or Application will not be responsible for the\n" +
                "            views or\n" +
                "            opinions expressed by third parties on the Site.\n" +
                "            You agree that you will not use any Post and/or any part or all of our Site and/or Application to:\n" +
                "            collect, store and/or identify private or personal information of any user or person;\n" +
                "            facilitate personal attacks on other individuals or groups of people;\n" +
                "            upload, post or e-mail any content that is defamatory, obscene, pornographic, threatening, harassing,\n" +
                "            unlawful,\n" +
                "            harmful, abusive, tortious, profane, hateful, or racially, ethnically or otherwise objectionable; and/or\n" +
                "            other\n" +
                "            information that the Site deems in its sole discretion inappropriate for the Site;\n" +
                "            harm children in any way including without limitation any offences in relation to grooming children online\n" +
                "            under\n" +
                "            law;\n" +
                "            impersonate any person or entity, falsely state or otherwise misrepresent your affiliation with a person or\n" +
                "            entity\n" +
                "            or disguise the origin of any content;\n" +
                "            stalk or otherwise harass another person or User;\n" +
                "            upload, post or e-mail any content that you do not have a right to transmit under any law or under\n" +
                "            contractual or\n" +
                "            fiduciary relationships;\n" +
                "            upload, post or e-mail any content that infringes any intellectual property rights or other third party\n" +
                "            rights of\n" +
                "            any party;\n" +
                "            upload, post or e-mail any unsolicited or unauthorised advertising, promotional materials, 'junk mail',\n" +
                "            'spam',\n" +
                "            'chain letters' or any other form of solicitation;\n" +
                "            upload, post or e-mail any content that contains computer viruses or any other computer code, files or\n" +
                "            programs\n" +
                "            designed to interrupt, destroy or limit the functionality of any computer software, hardware or\n" +
                "            telecommunications\n" +
                "            equipment and/or the Site;\n" +
                "            disrupt the normal flow of dialogue, cause a screen to 'scroll' faster than other users of the chat areas\n" +
                "            are able\n" +
                "            to type, or otherwise act in a manner that negatively affects other users' ability to engage in real time\n" +
                "            exchanges;\n" +
                "            and/or\n" +
                "            violate any applicable national or international laws or regulations.\n" +
                "\n" +
                "            You further agree that you may use the Site and Application for non-commercial purposes only. You may not\n" +
                "            submit\n" +
                "            Posts intended to promote and/or generate revenue for yourself and/or any third party business activity.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "\n" +
                "    \n" +
                "        <h3>9.Compatible Devices</h3>\n" +
                "        <p>\n" +
                "\n" +
                "            In order to be able view and use Content on the Service, You will need to use a personal computer,\n" +
                "            smartphone, or\n" +
                "            other device that meets the system and compatibility requirements that We establish from time to time and is\n" +
                "            otherwise capable of interacting with the Service (each such device, a \"Compatible Device\"). We may change\n" +
                "            the\n" +
                "            requirements for Compatible Devices from time to time and, in some cases, whether a device is (or remains) a\n" +
                "            Compatible Device may depend on software or systems provided or maintained by the device manufacturer or\n" +
                "            other third\n" +
                "            parties. As a result, devices that are Compatible Devices at one time may cease to be Compatible Devices in\n" +
                "            the\n" +
                "            future.\n" +
                "            This Application is available to handheld mobile devices running Apple iOS and Android OS Operating Systems.\n" +
                "            We will\n" +
                "            use reasonable efforts to make the Application available at all times. However, You acknowledge the\n" +
                "            Application is\n" +
                "            provided over the internet and mobile networks and so the quality and availability of the Application may be\n" +
                "            affected by factors outside Olly’s reasonable control.\n" +
                "            Olly does not accept any responsibility whatsoever for unavailability of the Application, or any difficulty\n" +
                "            or\n" +
                "            inability to download or access Content or any other communication system failure which may result in the\n" +
                "            Application being unavailable. Olly will not be responsible for any support or maintenance for the\n" +
                "            Application.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "\n" +
                "    \n" +
                "        <h3>10.System Requirements</h3>\n" +
                "        <p>\n" +
                "            In order to use the Application, you are required to have a compatible mobile telephone or handheld device,\n" +
                "            internet\n" +
                "            access, and the necessary minimum specifications ('Software Requirements'). The Software Requirements are as\n" +
                "            follows: Apple iOS devices running iOS 4 or iOS 5, and Android OS devices running Android OS 2.3 onwards;\n" +
                "            Language:\n" +
                "            English. The version of the Application software may be upgraded from time to time to add support for new\n" +
                "            functions\n" +
                "            and services.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>11.Restrictions on Use</h3>\n" +
                "        <p>\n" +
                "            As a condition of use, You agree to use the Services solely for lawful purposes and not to use the Services\n" +
                "            for any\n" +
                "            purpose that is prohibited by these Terms of Use. You are solely responsible for all of your activity in\n" +
                "            connection\n" +
                "            with the Services. Without derogating from your responsibility under any applicable law, and solely by way\n" +
                "            of\n" +
                "            example, you shall not (and shall not permit any third party to) either (a) take any action or (b) download,\n" +
                "            upload,\n" +
                "            submit, post, or otherwise distribute or facilitate distribution of any Content that:\n" +
                "            is illegal, threatening, abusive, invasive of any person’s privacy, harassing, defamatory, libellous, false,\n" +
                "            deceptive, fraudulent, misleading, untruthful, tortuous, obscene, offensive, pornographic, or otherwise\n" +
                "            inappropriate, as We may determine in Our sole discretion;\n" +
                "            violates any right of publicity, or other right of any person or entity, or any law or contractual\n" +
                "            obligation;\n" +
                "            infringes any patent, copyright, trademark or other intellectual property right of any person or entity ;\n" +
                "            constitutes unauthorized or unsolicited advertising;\n" +
                "            involves commercial activity not expressly permitted by Us; or\n" +
                "            contains any harmful or malicious computer codes, files or programs that are designed or intended to damage,\n" +
                "            disrupt, interfere with, or limit, the proper functionality of any software or hardware, or that enables to\n" +
                "            obtain\n" +
                "            unauthorized access to any system, data or other information.\n" +
                "            disrupts, interferes with or restricts the use of our site by other Users;\n" +
                "            reverse engineers, decompiles, copy or adapts any software or other code or scripts forming part of our\n" +
                "            Website;\n" +
                "            changes, modifies, deletes, interferes with or misuses data contained on our site and entered by or relating\n" +
                "            to any\n" +
                "            third party user of our Website.\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>12.Right to Cancellation in case of invalid information from User.</h3>\n" +
                "        <p>\n" +
                "            The User expressly undertakes to provide to Olly only correct and valid information while requesting for any\n" +
                "            services under this agreement, and not to make any misrepresentation of facts at all. Any default on part of\n" +
                "            the\n" +
                "            User would vitiate this agreement and shall disentitle the User from availing the services from Us.\n" +
                "            In case Olly discovers or has reasons to believe at any time during or after receiving a request for\n" +
                "            services from\n" +
                "            the User that the request for services is either unauthorized or the information provided by the User or any\n" +
                "            of them\n" +
                "            is not correct or that any fact has been misrepresented by him, Olly in its sole discretion shall have the\n" +
                "            unrestricted right to take any steps against the User(s), including cancellation of the bookings, etc.\n" +
                "            without any\n" +
                "            prior intimation to the User. In such an event, We shall not be responsible or liable for any loss or damage\n" +
                "            that\n" +
                "            may be caused to the User or any of them as a consequence of such cancellation of booking or services.\n" +
                "            The User unequivocally indemnifies Olly of any such claim or liability and shall not hold Us responsible for\n" +
                "            any\n" +
                "            loss or damage arising out of measures taken by Us for safeguarding its own interest and that of its genuine\n" +
                "            customers. This would also include Us denying/cancelling any bookings on account of suspected fraud\n" +
                "            transactions.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>13.Third Party Account Information.</h3>\n" +
                "        <p>\n" +
                "            By using the account access service in Olly Website and Application, the User authorizes Olly and its agents\n" +
                "            to\n" +
                "            access third party sites, including that of banks and other payment gateways, designated by them or on their\n" +
                "            behalf\n" +
                "            for retrieving requested information.\n" +
                "            While registering, the User will choose a personal identification number (“PIN”) and password and is\n" +
                "            responsible for\n" +
                "            maintaining the confidentiality of the PIN and/or password and the account.\n" +
                "            The User is fully responsible for all activities that occur while using their PIN and/or password or\n" +
                "            account. It is\n" +
                "            the duty of the User to notify Olly immediately in writing of any unauthorized use of their PIN and/or\n" +
                "            password or\n" +
                "            account or any other breach of security. Olly will not be liable for any loss that may be incurred by the\n" +
                "            User as a\n" +
                "            result of unauthorized use of his PIN and/or password or account, either with or without his knowledge. The\n" +
                "            User\n" +
                "            shall not use anyone else's password at any time.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>14.Intellectual Property Rights</h3>\n" +
                "        <p>\n" +
                "            This Website and its mobile Applications are owned by Millennial Card Technologies Private Limited. All\n" +
                "            rights to,\n" +
                "            title and interest in the Content available on/ via the Website and Application, the Website’s and\n" +
                "            Application’s\n" +
                "            look and feel, the designs, trademarks, service marks, and trade names displayed on the Website and\n" +
                "            Application, and\n" +
                "            the Website and Application URLs, are the property of Millennial Card Technologies Private Limited or its\n" +
                "            licensors,\n" +
                "            and are protected by copyrights, trademarks, patents, or other proprietary rights and laws.\n" +
                "            The Website and its mobile Applications and the Content are protected by copyright laws, and belong to Us or\n" +
                "            its\n" +
                "            partners, affiliates or contributors. The copyrights in the Content are owned by Us or other copyright\n" +
                "            owners who\n" +
                "            have authorized their use on the Website. You may not manipulate or alter the images or other Content on the\n" +
                "            Website\n" +
                "            in any way.\n" +
                "            We respect the intellectual property rights of others and expect you to do the same. We will respond to\n" +
                "            notices of\n" +
                "            alleged copyright infringement that comply with applicable law and are properly provided to Us. We reserve\n" +
                "            the right\n" +
                "            to remove Content alleged to be infringing without prior notice and at our sole discretion. In appropriate\n" +
                "            circumstances, We will also terminate a User’s account if the User is determined to be a repeat infringer.\n" +
                "            Our\n" +
                "            designated copyright agent for notice of alleged copyright infringement appearing on the Website is: [insert\n" +
                "            concerned email address here].\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>15.Disclaimer of Warranties</h3>\n" +
                "        <p>\n" +
                "            The Services are provided on an “as is” and “with all faults” basis, and without warranty or condition of\n" +
                "            any kind,\n" +
                "            either express or implied. Without limiting the foregoing, we explicitly disclaim any warranties, either\n" +
                "            express or\n" +
                "            implied, including without limitation, warranties of merchantability, and fitness for a particular purpose,\n" +
                "            non-infringement and quality of Service. We make no warranty that the Service will meet your expectations,\n" +
                "            be free\n" +
                "            from viruses, or that data and content obtained through the service will be accurate, reliable or current,\n" +
                "            or that\n" +
                "            the service will be available on an uninterrupted, secure, or error-free basis. You acknowledge and agree\n" +
                "            that the\n" +
                "            use of the Service is at your own discretion and sole risk and that the entire risk as to the results and\n" +
                "            performance of the Service, including, without limitation, any damages to your computer system, tablet,\n" +
                "            mobile\n" +
                "            device or data stored on it, is solely Yours.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>16.Limitation of Liability</h3>\n" +
                "        <p>\n" +
                "            You acknowledge and agree that in no event will We (including, without limitation, our affiliates and their\n" +
                "            respective officers, directors, employees and agents) be liable for any direct, indirect, special, punitive,\n" +
                "            incidental or consequential damages or losses (including, without limitation, damages for loss of business\n" +
                "            profits,\n" +
                "            business interruption, loss of programs or information, and the like) arising out of your use of or\n" +
                "            inability to use\n" +
                "            the service, or improper use of the Service, even if you have been advised of the possibility thereof and\n" +
                "            regardless\n" +
                "            of the form of action, whether in contract, tort, or otherwise. You further acknowledge and agree that we\n" +
                "            may change\n" +
                "            the Service in whole or in part in its sole discretion without notice to you and without any liability to\n" +
                "            you\n" +
                "            whatsoever in connection therewith.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>17.Governing law</h3>\n" +
                "        <p>\n" +
                "            These Terms of Use shall be governed by the laws of India, without regard to principles of conflicts of law.\n" +
                "            Disputes\n" +
                "            Any action arising out of or relating to these Terms of Use or Your use of the Services must be commenced in\n" +
                "            the\n" +
                "            local or high courts located in New Delhi (and You consent to the jurisdiction of those courts).\n" +
                "            Interpretation\n" +
                "            Headings are for convenience only and shall not be used to construe the terms of these Terms of Use. If any\n" +
                "            term of\n" +
                "            this Terms of Use is found invalid or unenforceable by any court of competent jurisdiction, that term will\n" +
                "            be\n" +
                "            severed from these Terms of Use. No failure or delay by Us in exercising any right hereunder will waive any\n" +
                "            further\n" +
                "            exercise of that right. Our rights and remedies hereunder are cumulative and not exclusive.\n" +
                "            Waiver\n" +
                "            Any failure on Our part to exercise any provision or right under these Terms of Use, shall not constitute a\n" +
                "            waiver\n" +
                "            by Us of that provision or right.\n" +
                "            Indemnity\n" +
                "            You agree to indemnify, defend and hold harmless Olly and its affiliates, agents, respective employees,\n" +
                "            directors,\n" +
                "            officers, agents, managers, vendors and suppliers from and against any liability, losses, claims, damages,\n" +
                "            demands,\n" +
                "            investigations, inquiries, suits, costs and expenses (including legal fee and costs incidental thereto)\n" +
                "            asserted\n" +
                "            against or incurred, that arise out of or otherwise relating to Your use of the Website and Application,\n" +
                "            including\n" +
                "            without limitation any obligation to be performed by You pursuant to these Terms of Use. Further, You agree\n" +
                "            to hold\n" +
                "            Olly harmless against any claims made by any third party due to, or arising out of or otherwise relating to\n" +
                "            Your use\n" +
                "            of the Website or Application, any claim arising out of damage caused to third party by You, breach of these\n" +
                "            Terms\n" +
                "            of Use by You, or Your violation of any rights of another, including any intellectual property rights.\n" +
                "            Further, You\n" +
                "            agree to hold Olly harmless against any claims made by any third party due to legal suits regarding the\n" +
                "            originality,\n" +
                "            copyright issues, Your violation of any third party right, including without limitation any copyright,\n" +
                "            property, or\n" +
                "            privacy right. This defense and indemnification obligation will survive these Terms of Use.\n" +
                "            Notwithstanding anything to the contrary, Our entire liability towards You under these Terms of Use or\n" +
                "            otherwise\n" +
                "            shall only be in connection with refund of the money charged from You for any particular product or service,\n" +
                "            under\n" +
                "            which the unlikely liability arises.\n" +
                "\n" +
                "        </p>\n" +
                "\n" +
                "    \n" +
                "        <h3>18.Contact Information</h3>\n" +
                "        <p>\n" +
                "            If You have any questions or concerns with respect to this Terms of Use or the Website or Application or any\n" +
                "            information contained on thereon, You may contact Us by writing to Us at [insert email address for contact].\n" +
                "            These\n" +
                "            Terms of Use supersede any previous versions\n" +
                "        </p>\n" +
                "\n" +
                "</body>\n" +
                "</html>"));
    }

    @Override
    public boolean onSupportNavigateUp() {
        OllyCreditApplication.getInstance().trackEvent(
                GlobalConstants.CATEGORY_TERMS_CONDITIONS,
                GlobalConstants.ACTION_BACK,
                GlobalConstants.LABLE_TO_HOME
        );
        return super.onSupportNavigateUp();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu, menu);

        MenuItem menuItem = menu.findItem(R.id.feedback_icon);

        if (menuItem != null) {
            HelperClass.tintMenuIcon(this, menuItem, R.color.white);
        }

        return true;
    }

}
